version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  server:
    container_name: server-container
    image: node:16
    working_dir: /app
    command: bash -c "npm install && npm run debug"
    restart: always
    ports:
      - "3000:3000"
      - "9222:9222"
    volumes:
      - ./dist:/app/dist
      - ./package.json:/app/package.json
    links:
      - mongo
    depends_on:
      - mongo
